region: us-east-1

function_name: puppy-lambda
handler: service.handler
role: puppy_lambda-role-g9lmil7k
description: Fetches puppies, builds a single JSON document, and stores it in S3
runtime: python3.7

timeout: 500
memory_size: 128
